#!/bin/bash
# Prepare project.
# 
# Optional parameter: other default settings 
#
source $COSI_BIN/helper_scripts || { echo "script not found" ; exit ; }
source $COSI_BIN/cosi_project.default.settings

[[ "$1" != "" ]] && source $1 && echo "$1" sourced

myread "What is the Type (CPS?) " TYPE
myread "The Cosi Version" COSIVERSION 
myread "The atmosphere" ATMOSPHERE 
myread "The username" USER 
myread "The Chemical Composition" CHEM_COMP 

DIR="`date '+%Y-%m-%d.%H-%M'`-cosi$COSIVER-$TYPE-$CHEM_COMP-$ATMOSPHERE-$USER"
echo "DIR= $DIR"
read -t 10 -p "Press enter or wait 10 seconds to continue. Press ^C to chancel"
mkdir -p "$DIR/fioss"
mkdir -p "$DIR/hminus"
mkdir -p "$DIR/lbkg"
mkdir -p "$DIR/scripts"
echo "DIR=$DIR
COSIVERSION=$COSIVERSION
ATMOSPHERE=$ATMOSPHERE
USER=$USER
CHEM_COMP=$CHEMCOMP
FIOSS_SETTINGS=$FIOSS_SETTINGS" > $DIR/README.SETTINGS

cp $HMINUS_SETTINGS $DIR/hminus.settings 
cp $FIOSS_SETTINGS $DIR/fioss.settings
cp $COSI_BIN/CARDS.HMINUS.TEMPLATE $DIR/hminus/CARDS.TEMPLATE
cp $COSI_BIN/CARDS.FIOSS.TEMPLATE $DIR/fioss/CARDS.TEMPLATE
