#!/bin/bash
currentDir=$(pwd)
exists=0
for folder in ./fioss/T* ; do         # Use ./* ... NEVER bare *
  if [ -d "$folder" ] ; then   # Check whether file exists.
    echo 'T* subfolders exist, proceeding.'
    exists=1
  fi
  if [ $exists -eq 1 ]; then
    break
  fi
done

subBins_folder="subBins"

if [ ! -d ./"$subBins_folder" ]; then
  echo "subBins folder does not exist, creating ""$(pwd)"/"$subBins_folder"
  mkdir -p ./"$subBins_folder" || exit
fi

for folder in fioss/T*; do(
  echo "Processing ""$folder"
  temperature=$(echo "$folder" | awk -F'/' '{print $( NF )}')
  mkdir -p ./"$subBins_folder"/"$temperature"
  cd "$subBins_folder"/"$temperature" || exit
  python /scratch/cernetic/AtmosphericParameters/reduce.py "$temperature" /scratch/cernetic/AtmosphericParameters/bins ~/Documents/sorting/lopa-sorting/"$1" 1
) &
done
wait

