#!/bin/bash

for folder in fioss/T*; do(
  subBins_folder="subBins"
  echo "Processing ""$folder"
  temperature=$(echo "$folder" | awk -F'/' '{print $( NF )}')
  mkdir -p ./"$subBins_folder"/"$temperature"
  cd "$subBins_folder"/"$temperature" || exit
	cat > job.sh <<- EOT 
	#!/bin/bash
	#PBS -q atlasq
	#PBS -N segment${temperature}
	#PBS -M cernetic@mps.mpg.de
	#PBS -j oe
	#PBS -l nodes=1:ppn=48
	#PBS -l walltime=2:00:00
	EOT
	cat >> job.sh <<- "EOT"

	# initialize modules environment
	. $MODULESHOME/init/bash

	# load module(s)
	module load intel

	# change to submit dir
	cd $PBS_O_WORKDIR

	# number of processes
	NP=$(cat $PBS_NODEFILE | wc -l)

	# number of processes per node
	PPN=$(($NP/$(cat $PBS_NODEFILE|uniq|wc -l)))

	# set number of hardware contexts
	export PSM_SHAREDCONTEXTS_MAX=$(((($PPN+3))/4))
	
	# start your job
	EOT
	cat >> job.sh <<- EOT
	python /home/cernetic/Documents/sorting/lopa-sorting/mergeLopa.py "$folder""/lopa" 48	
	# unload module(s)
	module unload intel
	EOT
	qsub job.sh
	rm -f job.sh
) &
done
wait
