#!/bin/bash
################################
## Kill hminus.exe processes which take more than MAX_TIME minutes to converge
##
## First wait for the first hminus.exe to appear, proceed once it has appeared
## Print number of processes currently running, their time and PID every 5 seconds
## Exit either when there are no more processes executing or after killing the remaining ones after $MAX_TIME
## 
## Usage:
##	set the MAX_TIME variable to your liking, default is 15 minutes
(
MAX_TIME=15 # time to wait before killing the process in minutes

number_of_processes=$(ps aux | pgrep hminus.exe | wc -l)
while [ "$number_of_processes" -eq 0 ]; do
	echo "No processes found yet, sleeping 10s."
	sleep 10
	number_of_processes=$(ps aux | pgrep hminus.exe | wc -l)
done

hminus_exists=1
while [ $hminus_exists -eq 1 ]; do
	number_of_processes=$(ps aux | pgrep hminus.exe | wc -l)
	if [ "$number_of_processes" -gt 0 ]; then
		time_elapsed=$(ps aux | grep hminus.exe | awk '{print $10}'| awk -F':' '{print $1}') #get the process run time
		time_elapsed=( $time_elapsed ) #transform string into an array
		unset time_elapsed[${#time_elapsed[@]}-1] #delete the last element of the array
		pid=$(ps aux | grep hminus.exe | awk '{print $2}') #repeat the same with process ID (PID)
		pid=( $pid )
		unset pid[${#pid[@]}-1]
		counter=0 # array index
		echo "Found ""$number_of_processes"" processes"
		for time in ${time_elapsed[*]}; # walk over the array of runtimes and kill if exceeding $MAX_TIME
		do
			if [ $((time)) -ge $((MAX_TIME)) ]; then
				echo 'Killing process with time: '"${time}"' minutes, pid: '"${pid[$counter]}"'.'
				kill -9 "${pid[$counter]}"
			else
				if [ "$time" -eq 1 ]; then
					echo Found a process with PID "${pid[$counter]}" running "for" "$time" minute.
				else
					echo Found a process with PID "${pid[$counter]}" running "for" "$time" minutes.
				fi
			fi
			counter=$(( counter + 1 ))
		done
		sleep 5
	fi

	if [ "$number_of_processes" -eq 0 ]; then
		echo number of processes is 0, exiting.
		hminus_exists=0
	fi

done
) &
##
## 
##	
################################

################################
## Prepare hminus and fioss directories and submit the job to a cluster
##
## Create and prepare hminus directory with the appropriate atmosphere
## Create and prepare fioss directory
## Create the job.sh file and submit it to a cluter
##
## Usage:
##	set the wavelength interval by changing the parameters of fioss_do2_cluster command 
##		fioss_do2_cluster BEGINNING STEP END

for file in atmospheres/*.atm;
do(
  folder_name=$(echo "$file" |awk -F'.' '{print $1}' | awk -F'/' '{print $2}') # from atmosphere filename atmospheres/T5500.atm generate folder name T5500
  echo 'Creating' "$folder_name"
  cp -r hminus/template hminus/"$folder_name" # create the hminus folder for this atmosphere
  cp "$file" hminus/"$folder_name"/FAL_VD # copy and rename atmosphere file
  cp "$file" hminus/"$folder_name"/TABLE # copy and rename atmosphere file
  #echo 'lte' > hminus/"$folder_name"/fort.99 # set hminus.exe parameters 
  cd hminus/"$folder_name"/ || exit
  ./hminus.exe # run hminus
  a=$(cat fort.99) # check the exit status
  if [ 'exit' = "$a" ] ; then # if the exit status is anything but 'exit' append 'failed' to the current folder name
  # otherwise prepare fioss
    echo 'hminus completed successfully'
    cd ../.. || exit
    if [ ! -d fioss ]; then
      echo 'fioss directory does not exist, creating'
      mkdir fioss
    fi
    echo "Running fioss_prepare for ""$folder_name"
    fioss_prepare "$folder_name" #prepare fioss with the same folder name in fioss/$folder_name
    cd fioss/"$folder_name" || exit
    cp ../CARDS.TEMPLATE.INTENSITY ./CARDS.TEMPLATE
    cp -r /scratch/cernetic/COSI ./
    # create a job.sh file that is used to submit the job to a cluster
    # if EOT has quotes ("") round it that means it will NOT expand variable names
    # in order to set an unique name for our run we have to expand the $folder_name variable 
	cat > job.sh <<- EOT 
	#!/bin/bash
	#PBS -q atlasq
	#PBS -N nessy${folder_name}
	#PBS -M cernetic@mps.mpg.de
	#PBS -j oe
	#PBS -l nodes=1:ppn=48
	#PBS -l walltime=2:00:00
	EOT
	cat >> job.sh <<- "EOT"
    # initialize modules environment
    . $MODULESHOME/init/bash

    # change to submit dir
    cd $PBS_O_WORKDIR

	# load module(s)
	module load intel
    
    # set up the variables
	export MAX_PROC=48
    opacity0="            ABLIN(i) = opacity*0"
    opacity="            ABLIN(i) = opacity"
    odf_path="      OPEN (UNIT=1312,FILE=trim('../')//trim(currentFile),STATUS='OLD', READONLY)"
	
    # detailed spectra for ODF generation
	sed -i "875s/.*/${opacity}/" COSI/cosi/inibl0.for
	rm -rf JOB* freq* ctrl* mdisp lopa &
    abc="      ODF = .FALSE."
	sed -i "856s/.*/${abc}/" COSI/cosi/inibl0.for
	rm -f COSI/out-intel-x86_64/*
	/usr/bin/make 64 -C COSI/cosi/
	cp COSI/out-intel-x86_64/fioss8.exe ./
    wait
	fioss_do2 800 10 9500
	python ~/Documents/sorting/lopa-sorting/mergeMdisp.py mdisp/ detailed_spectra &
    python ~/Documents/sorting/lopa-sorting/mergeLopa.py lopa 


    # kurucz spectra
    sed -i "866s@.*@${odf_path}@" COSI/cosi/inibl0.for
	rm -rf JOB* freq* ctrl* mdisp &
	python /scratch/cernetic/AtmosphericParameters/reduce.py /scratch/cernetic/AtmosphericParameters/bins ~/Documents/sorting/lopa-sorting/subBinsk $(nproc) &
    abc="      ODF = .TRUE."
    sed -i "856s/.*/${abc}/" COSI/cosi/inibl0.for
	rm -f COSI/out-intel-x86_64/*
	/usr/bin/make 64 -C COSI/cosi/
	cp COSI/out-intel-x86_64/fioss8.exe ./
    wait
	fioss_do2 900 10 9200
	python ~/Documents/sorting/lopa-sorting/mergeMdisp.py mdisp/ nessy_lines
 
    # continuum only spectra
	rm -rf JOB* freq* ctrl* mdisp &
	sed -i "875s/.*/${opacity0}/" COSI/cosi/inibl0.for
	rm -f COSI/out-intel-x86_64/*
	/usr/bin/make 64 -C COSI/cosi/
	cp COSI/out-intel-x86_64/fioss8.exe ./
    wait
	fioss_do2 900 10 9200
	python ~/Documents/sorting/lopa-sorting/mergeMdisp.py mdisp/ nessy_continuum_only
	

	# start your job
	EOT
	cat >> job.sh <<- "EOT"
	
	
	# unload module(s)
	module unload intel
	EOT
    qsub job.sh # submit the job to the cluster
  else
    echo "Problem with atmosphere" "$file"
    cd .. || exit
    mv "$folder_name" "$folder_name""failed"
    cd .. || exit
  fi
  ) &
done
##
##
##
################################
wait
echo "All done, use 'qstat' to check the jobs queued on the cluster."
