#!/bin/bash
cd /scratch/mcernet/testRun/ || exit
rm -rf job*.sh
number_of_lines="$(cat subBinList | wc -l)"
readarray subBins < ./subBinList
#echo $number_of_lines
for ((i=0;i<number_of_lines;i++));do
job_name=$(echo "${subBins[i]}"|tr -d '\n')
cat > job"$i".sh <<- EOT 
	#!/bin/sh
	#BSUB -q mpi-short
	#BSUB -n 24
	#BSUB -R "span[hosts=1]"
	#BSUB -R scratch
	#BSUB -W 02:00
	#BSUB -o out.%J

	EOT
	cat >> job"$i".sh <<- "EOT"
	EOT
	cat >> job"$i".sh <<- EOT
	# start your job
		compareSubbins $job_name
		python interpolation.py /scratch/mcernet/lopa-sorting/$job_name 24
	EOT
done	
for file in job*.sh;do
   bsub < "$file"
done
